### PR TITLE
Feat: adding ability to remove slack specific content and branding

### PR DESCRIPTION
**Pull request by jeffjenk**
Since some users might not know what slack is, I am proposing a way to hide slack specific content and branding from the plugin. I think the best way to achieve this is with a simple boolean property 'hideSlack'. The component will still push messages to slack but the user doesn't need to know that.

### CODE REVIEW

**Comment by jeffjenk** [comment]
Thanks so much for this plugin by the way. Simple, well coded and damn good looking!

**Comment by markmur** [comment]
Thanks for the PR @jeffjenk.

Rather than a `hideSlack` prop, I think I'd rather multiple props which let the user customise the content.

For example:

- A `trigger` prop which lets the user customise the contents of the trigger button:

```javascript
<SlackFeedback trigger={<span><SomeOtherIcon /> Trigger Text</span>} />
```

- A `showChannel`  bool prop which defaults to true.

- A `title` prop which can be used to change the header text

**Comment by jeffjenk** [comment]
Hey @markmur,
Yes that makes a lot of sense, I will make the recommended changes and resubmit.

**Comment by jeffjenk** [comment]
Okay, `showChannel` and `title` props added.

The trigger already has `buttonText` so i thought perhaps it would be better to make a new prop `icon` for the icon itself? That way you can override the icon and have it replaced in both places that it is used or simply replace it with and empty prop to remove it.

**Comment by markmur** [comment]
Thanks for the updates @jeffjenk. I'm not a big fan of the `icon` prop because it controls the icon in the trigger and the header, I'd rather have the `buttonText` prop change the entire trigger, and default to `<SlackIcon /> Slack Feedback`, and similarly the `title` prop would default to `<SlackIcon> Send Feedback to Slack`

**Comment by jeffjenk** [comment]
Hi Mark. Sure, I think thats better too. I will make the recommended changes.

**Comment by jeffjenk** [comment]
Hi Mark. Sorry for the long delay on this. I have implemented your recommended changes.

**Pull request merged**
